version: "3"
services:

  #purchase
  purchases_container:
    container_name: purchases_container
    image: ghcr.io/idacjohansson/order:latest
    ports:
      - "3308:3306"
    environment:
      MYSQL_USER: springuser
      MYSQL_DATABASE: purchases_db
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      restart: always

  customer-db:
    # build: .
    image: mysql
    ports:
      - "3309:3306"
    environment:
      MYSQL_USER: micro_user
      MYSQL_PASSWORD: micro_password
      MYSQL_DB: micro_db
      #depends_on:
      restart: always

  item-db:
    # build: .
    image: mysql
    ports:
      - "3310:3306"
    environment:
      MYSQL_USER: item_user
      MYSQL_PASSWORD: item_password
      MYSQL_DB: item_db
      #depends_on:
      restart: always